# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'doc/*'

# repos
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    #-   id: check-added-large-files
-   repo: local
    hooks:
    -   id: tox
        name: tox
        entry: tox
        language: system
        pass_filenames: false
        types: [python]

    #-   id: mypy
    #    name: mypy
    #    entry: mypy
    #    stages: [commit]
    #    language: system
    #    pass_filenames: false
    #    types: [python]

    -   id: isort
        name: isort
        entry: isort
        stages: [commit]
        language: system
        types: [python]

    -   id: black
        name: black
        entry: black
        stages: [commit]
        language: system
        types: [python]

    -   id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        stages: [commit]
        language: system
        types: [python]
